onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /mp3_w_l1cache_tb/clk
add wave -noupdate -radix hexadecimal -childformat {{{/mp3_w_l1cache_tb/dut/CPU/regfile/data[7]} -radix hexadecimal} {{/mp3_w_l1cache_tb/dut/CPU/regfile/data[6]} -radix hexadecimal} {{/mp3_w_l1cache_tb/dut/CPU/regfile/data[5]} -radix hexadecimal} {{/mp3_w_l1cache_tb/dut/CPU/regfile/data[4]} -radix hexadecimal} {{/mp3_w_l1cache_tb/dut/CPU/regfile/data[3]} -radix hexadecimal} {{/mp3_w_l1cache_tb/dut/CPU/regfile/data[2]} -radix hexadecimal} {{/mp3_w_l1cache_tb/dut/CPU/regfile/data[1]} -radix hexadecimal} {{/mp3_w_l1cache_tb/dut/CPU/regfile/data[0]} -radix hexadecimal}} -expand -subitemconfig {{/mp3_w_l1cache_tb/dut/CPU/regfile/data[7]} {-height 15 -radix hexadecimal} {/mp3_w_l1cache_tb/dut/CPU/regfile/data[6]} {-height 15 -radix hexadecimal} {/mp3_w_l1cache_tb/dut/CPU/regfile/data[5]} {-height 15 -radix hexadecimal} {/mp3_w_l1cache_tb/dut/CPU/regfile/data[4]} {-height 15 -radix hexadecimal} {/mp3_w_l1cache_tb/dut/CPU/regfile/data[3]} {-height 15 -radix hexadecimal} {/mp3_w_l1cache_tb/dut/CPU/regfile/data[2]} {-height 15 -radix hexadecimal} {/mp3_w_l1cache_tb/dut/CPU/regfile/data[1]} {-height 15 -radix hexadecimal} {/mp3_w_l1cache_tb/dut/CPU/regfile/data[0]} {-height 15 -radix hexadecimal}} /mp3_w_l1cache_tb/dut/CPU/regfile/data
add wave -noupdate -color {Medium Slate Blue} -radix hexadecimal /mp3_w_l1cache_tb/dut/CPU/pc/data
add wave -noupdate -color Turquoise -expand -subitemconfig {{/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_0/data[15]} {-color Turquoise} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_0/data[14]} {-color Turquoise} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_0/data[13]} {-color Turquoise} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_0/data[12]} {-color Turquoise} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_0/data[11]} {-color Turquoise} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_0/data[10]} {-color Turquoise} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_0/data[9]} {-color Turquoise} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_0/data[8]} {-color Turquoise} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_0/data[7]} {-color Turquoise -height 15} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_0/data[6]} {-color Turquoise -height 15} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_0/data[5]} {-color Turquoise -height 15} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_0/data[4]} {-color Turquoise -height 15} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_0/data[3]} {-color Turquoise -height 15} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_0/data[2]} {-color Turquoise -height 15} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_0/data[1]} {-color Turquoise -height 15} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_0/data[0]} {-color Turquoise -height 15}} /mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_0/data
add wave -noupdate -color Turquoise -expand -subitemconfig {{/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_1/data[15]} {-color Turquoise} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_1/data[14]} {-color Turquoise} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_1/data[13]} {-color Turquoise} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_1/data[12]} {-color Turquoise} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_1/data[11]} {-color Turquoise} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_1/data[10]} {-color Turquoise} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_1/data[9]} {-color Turquoise} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_1/data[8]} {-color Turquoise} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_1/data[7]} {-color Turquoise -height 15} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_1/data[6]} {-color Turquoise -height 15} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_1/data[5]} {-color Turquoise -height 15} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_1/data[4]} {-color Turquoise -height 15} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_1/data[3]} {-color Turquoise -height 15} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_1/data[2]} {-color Turquoise -height 15} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_1/data[1]} {-color Turquoise -height 15} {/mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_1/data[0]} {-color Turquoise -height 15}} /mp3_w_l1cache_tb/dut/icache/cache_datapath/data_array_1/data
add wave -noupdate -color {Medium Slate Blue} -expand -subitemconfig {{/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_0/data[15]} {-color {Medium Slate Blue}} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_0/data[14]} {-color {Medium Slate Blue}} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_0/data[13]} {-color {Medium Slate Blue}} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_0/data[12]} {-color {Medium Slate Blue}} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_0/data[11]} {-color {Medium Slate Blue}} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_0/data[10]} {-color {Medium Slate Blue}} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_0/data[9]} {-color {Medium Slate Blue}} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_0/data[8]} {-color {Medium Slate Blue}} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_0/data[7]} {-color {Medium Slate Blue} -height 14} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_0/data[6]} {-color {Medium Slate Blue} -height 14} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_0/data[5]} {-color {Medium Slate Blue} -height 14} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_0/data[4]} {-color {Medium Slate Blue} -height 14} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_0/data[3]} {-color {Medium Slate Blue} -height 14} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_0/data[2]} {-color {Medium Slate Blue} -height 14} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_0/data[1]} {-color {Medium Slate Blue} -height 14} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_0/data[0]} {-color {Medium Slate Blue} -height 14}} /mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_0/data
add wave -noupdate -color {Medium Slate Blue} -expand -subitemconfig {{/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_1/data[15]} {-color {Medium Slate Blue}} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_1/data[14]} {-color {Medium Slate Blue}} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_1/data[13]} {-color {Medium Slate Blue}} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_1/data[12]} {-color {Medium Slate Blue}} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_1/data[11]} {-color {Medium Slate Blue}} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_1/data[10]} {-color {Medium Slate Blue}} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_1/data[9]} {-color {Medium Slate Blue}} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_1/data[8]} {-color {Medium Slate Blue}} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_1/data[7]} {-color {Medium Slate Blue} -height 14} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_1/data[6]} {-color {Medium Slate Blue} -height 14} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_1/data[5]} {-color {Medium Slate Blue} -height 14} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_1/data[4]} {-color {Medium Slate Blue} -height 14} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_1/data[3]} {-color {Medium Slate Blue} -height 14} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_1/data[2]} {-color {Medium Slate Blue} -height 14} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_1/data[1]} {-color {Medium Slate Blue} -height 14} {/mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_1/data[0]} {-color {Medium Slate Blue} -height 14}} /mp3_w_l1cache_tb/dut/dcache/cache_datapath/data_array_1/data
add wave -noupdate -color {Orange Red} /mp3_w_l1cache_tb/dut/l2cache/l2_control/curr_state
add wave -noupdate /mp3_w_l1cache_tb/dut/l2cache/l2_control/replace
add wave -noupdate -color Khaki -expand -subitemconfig {{/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_0/data[7]} {-color Khaki -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_0/data[6]} {-color Khaki -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_0/data[5]} {-color Khaki -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_0/data[4]} {-color Khaki -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_0/data[3]} {-color Khaki -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_0/data[2]} {-color Khaki -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_0/data[1]} {-color Khaki -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_0/data[0]} {-color Khaki -height 14}} /mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_0/data
add wave -noupdate -color Tan -expand -subitemconfig {{/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_1/data[7]} {-color Tan -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_1/data[6]} {-color Tan -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_1/data[5]} {-color Tan -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_1/data[4]} {-color Tan -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_1/data[3]} {-color Tan -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_1/data[2]} {-color Tan -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_1/data[1]} {-color Tan -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_1/data[0]} {-color Tan -height 14}} /mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_1/data
add wave -noupdate -color Goldenrod -expand -subitemconfig {{/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_2/data[7]} {-color Goldenrod -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_2/data[6]} {-color Goldenrod -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_2/data[5]} {-color Goldenrod -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_2/data[4]} {-color Goldenrod -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_2/data[3]} {-color Goldenrod -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_2/data[2]} {-color Goldenrod -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_2/data[1]} {-color Goldenrod -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_2/data[0]} {-color Goldenrod -height 14}} /mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_2/data
add wave -noupdate -color Coral -expand -subitemconfig {{/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_3/data[7]} {-color Coral -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_3/data[6]} {-color Coral -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_3/data[5]} {-color Coral -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_3/data[4]} {-color Coral -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_3/data[3]} {-color Coral -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_3/data[2]} {-color Coral -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_3/data[1]} {-color Coral -height 14} {/mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_3/data[0]} {-color Coral -height 14}} /mp3_w_l1cache_tb/dut/l2cache/l2_datapath/data_array_3/data
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {9282810 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 140
configure wave -valuecolwidth 86
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {596017464 ps} {600209608 ps}
